### ISSUE TITLE
please consider avoiding AtomicU64 unsupported on some arches

### ISSUE THREAD

**Issue by jonassmedegaard** [sagebind/threadfin#3]
Threadfin uses AtomicU64 which is unsupported on armv5te and mipsel.

Please consider avoiding that, to cover more architectures.

**Comment by sagebind** [comment]
Thanks for opening an issue! This definitely seems like a good thing that ought to be fixed. I will see about getting a PR opened to fix this in a few days time if I can.

**Comment by jonassmedegaard** [comment]
Perhaps use [portable-atomic](https://lib.rs/crates/portable-atomic)?

**Comment by sagebind** [comment]
This should now be fixed in [version 0.1.2](https://github.com/sagebind/threadfin/releases/tag/0.1.2).
